# .air.taskrunner.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/taskrunner ./cmd/taskrunner"
bin = "tmp/taskrunner"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]

[log]
time_format = "15:04:05"